/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'slug' : string,
  'metaTitle' : string,
  'timestamp' : bigint,
}
export interface CategoriesResult {
  'data' : [] | [Array<ProjectCategory>],
  'error' : [] | [string],
  'success' : boolean,
}
export interface CategoryResult {
  'data' : [] | [ProjectCategory],
  'error' : [] | [string],
  'success' : boolean,
}
export type ClaimAdminResult = { 'notAuthenticated' : null } |
  { 'success' : null } |
  { 'alreadyClaimed' : null };
export interface CrudResponse {
  'data' : [] | [boolean],
  'error' : [] | [string],
  'success' : boolean,
}
export interface Experience {
  'id' : bigint,
  'title' : string,
  'responsibilities' : Array<string>,
  'period' : string,
  'description' : string,
  'company' : string,
}
export interface ExperienceResult {
  'data' : [] | [Experience],
  'error' : [] | [string],
  'success' : boolean,
}
export interface ExperiencesResult {
  'data' : [] | [Array<Experience>],
  'error' : [] | [string],
  'success' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface Lead {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Project {
  'id' : bigint,
  'url' : string,
  'categoryId' : [] | [bigint],
  'title' : string,
  'order' : bigint,
  'description' : string,
  'isActive' : boolean,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface ProjectCategory {
  'id' : bigint,
  'order' : bigint,
  'name' : string,
  'slug' : string,
}
export interface ProjectResult {
  'data' : [] | [Project],
  'error' : [] | [string],
  'success' : boolean,
}
export interface ProjectsResult {
  'data' : [] | [Array<Project>],
  'error' : [] | [string],
  'success' : boolean,
}
export interface SeoSetting {
  'metaDescription' : string,
  'page' : string,
  'metaTitle' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export interface ServiceResult {
  'data' : [] | [Service],
  'error' : [] | [string],
  'success' : boolean,
}
export interface ServicesResult {
  'data' : [] | [Array<Service>],
  'error' : [] | [string],
  'success' : boolean,
}
export interface Skill {
  'id' : bigint,
  'name' : string,
  'experience' : bigint,
  'category' : SkillCategory,
}
export type SkillCategory = { 'security' : null } |
  { 'secondary' : null } |
  { 'primary' : null } |
  { 'additional' : null };
export interface SocialLink {
  'id' : bigint,
  'url' : string,
  'icon' : string,
  'platform' : SocialPlatform,
  'isActive' : boolean,
}
export type SocialPlatform = { 'x' : null } |
  { 'linkedin' : null } |
  { 'github' : null };
export interface Testimonial {
  'id' : bigint,
  'author' : string,
  'message' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string],
    BlogPost
  >,
  'addExperience' : ActorMethod<
    [string, string, string, string, Array<string>],
    ExperienceResult
  >,
  'addProject' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [bigint],
      bigint,
      boolean,
    ],
    ProjectResult
  >,
  'addProjectCategory' : ActorMethod<[string, string, bigint], CategoryResult>,
  'addService' : ActorMethod<[string, string], ServiceResult>,
  'addSkill' : ActorMethod<[string, bigint, SkillCategory], Skill>,
  'addSocialLink' : ActorMethod<
    [SocialPlatform, string, string, boolean],
    SocialLink
  >,
  'addTestimonial' : ActorMethod<[string, string], Testimonial>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], ClaimAdminResult>,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'deleteExperience' : ActorMethod<[bigint], CrudResponse>,
  'deleteLead' : ActorMethod<[bigint], boolean>,
  'deleteProject' : ActorMethod<[bigint], CrudResponse>,
  'deleteProjectCategory' : ActorMethod<[bigint], CrudResponse>,
  'deleteService' : ActorMethod<[bigint], CrudResponse>,
  'deleteSkill' : ActorMethod<[bigint], boolean>,
  'deleteSocialLink' : ActorMethod<[bigint], boolean>,
  'deleteTestimonial' : ActorMethod<[bigint], boolean>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExperiences' : ActorMethod<[], ExperiencesResult>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getProject' : ActorMethod<[bigint], ProjectResult>,
  'getProjectCategories' : ActorMethod<[], CategoriesResult>,
  'getProjects' : ActorMethod<[], ProjectsResult>,
  'getSeoSetting' : ActorMethod<[string], [] | [SeoSetting]>,
  'getSeoSettings' : ActorMethod<[], Array<SeoSetting>>,
  'getServices' : ActorMethod<[], ServicesResult>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'getSocialLinks' : ActorMethod<[], Array<SocialLink>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderProjects' : ActorMethod<[Array<bigint>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSeoSetting' : ActorMethod<[string, string, string], SeoSetting>,
  'submitLead' : ActorMethod<[string, string, string], Lead>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string],
    [] | [BlogPost]
  >,
  'updateExperience' : ActorMethod<
    [bigint, string, string, string, string, Array<string>],
    ExperienceResult
  >,
  'updateProject' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [bigint],
      bigint,
      boolean,
    ],
    ProjectResult
  >,
  'updateProjectCategory' : ActorMethod<
    [bigint, string, string, bigint],
    CategoryResult
  >,
  'updateService' : ActorMethod<[bigint, string, string], ServiceResult>,
  'updateSkill' : ActorMethod<
    [bigint, string, bigint, SkillCategory],
    [] | [Skill]
  >,
  'updateSocialLink' : ActorMethod<
    [bigint, SocialPlatform, string, string, boolean],
    [] | [SocialLink]
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string],
    [] | [Testimonial]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];