/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'metaTitle' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Experience = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'responsibilities' : IDL.Vec(IDL.Text),
  'period' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
});
export const ExperienceResult = IDL.Record({
  'data' : IDL.Opt(Experience),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'categoryId' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
});
export const ProjectResult = IDL.Record({
  'data' : IDL.Opt(Project),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const ProjectCategory = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const CategoryResult = IDL.Record({
  'data' : IDL.Opt(ProjectCategory),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ServiceResult = IDL.Record({
  'data' : IDL.Opt(Service),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const SkillCategory = IDL.Variant({
  'security' : IDL.Null,
  'secondary' : IDL.Null,
  'primary' : IDL.Null,
  'additional' : IDL.Null,
});
export const Skill = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'experience' : IDL.Int,
  'category' : SkillCategory,
});
export const SocialPlatform = IDL.Variant({
  'x' : IDL.Null,
  'linkedin' : IDL.Null,
  'github' : IDL.Null,
});
export const SocialLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'icon' : IDL.Text,
  'platform' : SocialPlatform,
  'isActive' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Text,
  'message' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClaimAdminResult = IDL.Variant({
  'notAuthenticated' : IDL.Null,
  'success' : IDL.Null,
  'alreadyClaimed' : IDL.Null,
});
export const CrudResponse = IDL.Record({
  'data' : IDL.Opt(IDL.Bool),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ExperiencesResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(Experience)),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const CategoriesResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(ProjectCategory)),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const ProjectsResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(Project)),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const SeoSetting = IDL.Record({
  'metaDescription' : IDL.Text,
  'page' : IDL.Text,
  'metaTitle' : IDL.Text,
});
export const ServicesResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(Service)),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BlogPost],
      [],
    ),
  'addExperience' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [ExperienceResult],
      [],
    ),
  'addProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Nat),
        IDL.Nat,
        IDL.Bool,
      ],
      [ProjectResult],
      [],
    ),
  'addProjectCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [CategoryResult],
      [],
    ),
  'addService' : IDL.Func([IDL.Text, IDL.Text], [ServiceResult], []),
  'addSkill' : IDL.Func([IDL.Text, IDL.Int, SkillCategory], [Skill], []),
  'addSocialLink' : IDL.Func(
      [SocialPlatform, IDL.Text, IDL.Text, IDL.Bool],
      [SocialLink],
      [],
    ),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [Testimonial], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdmin' : IDL.Func([], [ClaimAdminResult], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteExperience' : IDL.Func([IDL.Nat], [CrudResponse], []),
  'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Nat], [CrudResponse], []),
  'deleteProjectCategory' : IDL.Func([IDL.Nat], [CrudResponse], []),
  'deleteService' : IDL.Func([IDL.Nat], [CrudResponse], []),
  'deleteSkill' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSocialLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExperiences' : IDL.Func([], [ExperiencesResult], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [ProjectResult], ['query']),
  'getProjectCategories' : IDL.Func([], [CategoriesResult], ['query']),
  'getProjects' : IDL.Func([], [ProjectsResult], ['query']),
  'getSeoSetting' : IDL.Func([IDL.Text], [IDL.Opt(SeoSetting)], ['query']),
  'getSeoSettings' : IDL.Func([], [IDL.Vec(SeoSetting)], ['query']),
  'getServices' : IDL.Func([], [ServicesResult], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSeoSetting' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [SeoSetting], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Lead], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(BlogPost)],
      [],
    ),
  'updateExperience' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [ExperienceResult],
      [],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Nat),
        IDL.Nat,
        IDL.Bool,
      ],
      [ProjectResult],
      [],
    ),
  'updateProjectCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [CategoryResult],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [ServiceResult],
      [],
    ),
  'updateSkill' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Int, SkillCategory],
      [IDL.Opt(Skill)],
      [],
    ),
  'updateSocialLink' : IDL.Func(
      [IDL.Nat, SocialPlatform, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Opt(SocialLink)],
      [],
    ),
  'updateTestimonial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(Testimonial)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'metaTitle' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Experience = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'responsibilities' : IDL.Vec(IDL.Text),
    'period' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
  });
  const ExperienceResult = IDL.Record({
    'data' : IDL.Opt(Experience),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'categoryId' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
  });
  const ProjectResult = IDL.Record({
    'data' : IDL.Opt(Project),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const ProjectCategory = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const CategoryResult = IDL.Record({
    'data' : IDL.Opt(ProjectCategory),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServiceResult = IDL.Record({
    'data' : IDL.Opt(Service),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const SkillCategory = IDL.Variant({
    'security' : IDL.Null,
    'secondary' : IDL.Null,
    'primary' : IDL.Null,
    'additional' : IDL.Null,
  });
  const Skill = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'experience' : IDL.Int,
    'category' : SkillCategory,
  });
  const SocialPlatform = IDL.Variant({
    'x' : IDL.Null,
    'linkedin' : IDL.Null,
    'github' : IDL.Null,
  });
  const SocialLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'icon' : IDL.Text,
    'platform' : SocialPlatform,
    'isActive' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Text,
    'message' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClaimAdminResult = IDL.Variant({
    'notAuthenticated' : IDL.Null,
    'success' : IDL.Null,
    'alreadyClaimed' : IDL.Null,
  });
  const CrudResponse = IDL.Record({
    'data' : IDL.Opt(IDL.Bool),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ExperiencesResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(Experience)),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const CategoriesResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(ProjectCategory)),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const ProjectsResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(Project)),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const SeoSetting = IDL.Record({
    'metaDescription' : IDL.Text,
    'page' : IDL.Text,
    'metaTitle' : IDL.Text,
  });
  const ServicesResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(Service)),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BlogPost],
        [],
      ),
    'addExperience' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [ExperienceResult],
        [],
      ),
    'addProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Nat),
          IDL.Nat,
          IDL.Bool,
        ],
        [ProjectResult],
        [],
      ),
    'addProjectCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [CategoryResult],
        [],
      ),
    'addService' : IDL.Func([IDL.Text, IDL.Text], [ServiceResult], []),
    'addSkill' : IDL.Func([IDL.Text, IDL.Int, SkillCategory], [Skill], []),
    'addSocialLink' : IDL.Func(
        [SocialPlatform, IDL.Text, IDL.Text, IDL.Bool],
        [SocialLink],
        [],
      ),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [Testimonial], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdmin' : IDL.Func([], [ClaimAdminResult], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteExperience' : IDL.Func([IDL.Nat], [CrudResponse], []),
    'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Nat], [CrudResponse], []),
    'deleteProjectCategory' : IDL.Func([IDL.Nat], [CrudResponse], []),
    'deleteService' : IDL.Func([IDL.Nat], [CrudResponse], []),
    'deleteSkill' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSocialLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExperiences' : IDL.Func([], [ExperiencesResult], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [ProjectResult], ['query']),
    'getProjectCategories' : IDL.Func([], [CategoriesResult], ['query']),
    'getProjects' : IDL.Func([], [ProjectsResult], ['query']),
    'getSeoSetting' : IDL.Func([IDL.Text], [IDL.Opt(SeoSetting)], ['query']),
    'getSeoSettings' : IDL.Func([], [IDL.Vec(SeoSetting)], ['query']),
    'getServices' : IDL.Func([], [ServicesResult], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSeoSetting' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SeoSetting],
        [],
      ),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Lead], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(BlogPost)],
        [],
      ),
    'updateExperience' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [ExperienceResult],
        [],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Nat),
          IDL.Nat,
          IDL.Bool,
        ],
        [ProjectResult],
        [],
      ),
    'updateProjectCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [CategoryResult],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [ServiceResult],
        [],
      ),
    'updateSkill' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int, SkillCategory],
        [IDL.Opt(Skill)],
        [],
      ),
    'updateSocialLink' : IDL.Func(
        [IDL.Nat, SocialPlatform, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Opt(SocialLink)],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(Testimonial)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };