/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SkillCategory = IDL.Variant({
  'security' : IDL.Null,
  'secondary' : IDL.Null,
  'primary' : IDL.Null,
  'additional' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClaimAdminResult = IDL.Variant({
  'notAuthenticated' : IDL.Null,
  'success' : IDL.Null,
  'alreadyClaimed' : IDL.Null,
});
export const ProjectCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const CategoryResult = IDL.Record({
  'data' : IDL.Opt(ProjectCategory),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'categoryId' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
});
export const ProjectResult = IDL.Record({
  'data' : IDL.Opt(Project),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ServiceResult = IDL.Record({
  'data' : IDL.Opt(Service),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const SocialPlatform = IDL.Variant({
  'x' : IDL.Null,
  'linkedin' : IDL.Null,
  'github' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'metaTitle' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SeoSetting = IDL.Record({
  'metaDescription' : IDL.Text,
  'page' : IDL.Text,
  'metaTitle' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Text,
  'message' : IDL.Text,
});
export const CategoriesResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(ProjectCategory)),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const ProjectsResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(Project)),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const ServicesResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(Service)),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Skill = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'experience' : IDL.Int,
  'category' : SkillCategory,
});
export const SocialLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'icon' : IDL.Text,
  'platform' : SocialPlatform,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addSkill' : IDL.Func([IDL.Text, IDL.Int, SkillCategory], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'claimAdmin' : IDL.Func([], [ClaimAdminResult], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryResult], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Nat)],
      [ProjectResult],
      [],
    ),
  'createService' : IDL.Func([IDL.Text, IDL.Text], [ServiceResult], []),
  'createSocialLink' : IDL.Func([SocialPlatform, IDL.Text, IDL.Text], [], []),
  'deleteBlog' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [CategoryResult], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [ProjectResult], []),
  'deleteSeoSetting' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [ServiceResult], []),
  'deleteSkill' : IDL.Func([IDL.Nat], [], []),
  'deleteSocialLink' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Nat], [CategoryResult], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'leadCount' : IDL.Nat,
          'projectCount' : IDL.Nat,
          'blogCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [ProjectResult], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSeoSettingByPage' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SeoSetting)],
      ['query'],
    ),
  'getSeoSettings' : IDL.Func([], [IDL.Vec(SeoSetting)], ['query']),
  'getService' : IDL.Func([IDL.Nat], [ServiceResult], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [CategoriesResult], ['query']),
  'listProjects' : IDL.Func([], [ProjectsResult], ['query']),
  'listServices' : IDL.Func([], [ServicesResult], ['query']),
  'listSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'listSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
  'processContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'resetAdmin' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSeoSetting' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'toggleSocialLink' : IDL.Func([IDL.Nat], [], []),
  'updateBlog' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [CategoryResult],
      [],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Nat),
      ],
      [ProjectResult],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [ServiceResult],
      [],
    ),
  'updateSkill' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int, SkillCategory], [], []),
  'updateSocialLink' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateTestimonial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SkillCategory = IDL.Variant({
    'security' : IDL.Null,
    'secondary' : IDL.Null,
    'primary' : IDL.Null,
    'additional' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClaimAdminResult = IDL.Variant({
    'notAuthenticated' : IDL.Null,
    'success' : IDL.Null,
    'alreadyClaimed' : IDL.Null,
  });
  const ProjectCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const CategoryResult = IDL.Record({
    'data' : IDL.Opt(ProjectCategory),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'categoryId' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
  });
  const ProjectResult = IDL.Record({
    'data' : IDL.Opt(Project),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServiceResult = IDL.Record({
    'data' : IDL.Opt(Service),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const SocialPlatform = IDL.Variant({
    'x' : IDL.Null,
    'linkedin' : IDL.Null,
    'github' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'metaTitle' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SeoSetting = IDL.Record({
    'metaDescription' : IDL.Text,
    'page' : IDL.Text,
    'metaTitle' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Text,
    'message' : IDL.Text,
  });
  const CategoriesResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(ProjectCategory)),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const ProjectsResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(Project)),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const ServicesResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(Service)),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Skill = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'experience' : IDL.Int,
    'category' : SkillCategory,
  });
  const SocialLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'icon' : IDL.Text,
    'platform' : SocialPlatform,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addSkill' : IDL.Func([IDL.Text, IDL.Int, SkillCategory], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'claimAdmin' : IDL.Func([], [ClaimAdminResult], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryResult], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Nat)],
        [ProjectResult],
        [],
      ),
    'createService' : IDL.Func([IDL.Text, IDL.Text], [ServiceResult], []),
    'createSocialLink' : IDL.Func([SocialPlatform, IDL.Text, IDL.Text], [], []),
    'deleteBlog' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [CategoryResult], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [ProjectResult], []),
    'deleteSeoSetting' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [ServiceResult], []),
    'deleteSkill' : IDL.Func([IDL.Nat], [], []),
    'deleteSocialLink' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Nat], [CategoryResult], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'leadCount' : IDL.Nat,
            'projectCount' : IDL.Nat,
            'blogCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [ProjectResult], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSeoSettingByPage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SeoSetting)],
        ['query'],
      ),
    'getSeoSettings' : IDL.Func([], [IDL.Vec(SeoSetting)], ['query']),
    'getService' : IDL.Func([IDL.Nat], [ServiceResult], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [CategoriesResult], ['query']),
    'listProjects' : IDL.Func([], [ProjectsResult], ['query']),
    'listServices' : IDL.Func([], [ServicesResult], ['query']),
    'listSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'listSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
    'processContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'resetAdmin' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSeoSetting' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'toggleSocialLink' : IDL.Func([IDL.Nat], [], []),
    'updateBlog' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [CategoryResult],
        [],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Nat),
        ],
        [ProjectResult],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [ServiceResult],
        [],
      ),
    'updateSkill' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int, SkillCategory],
        [],
        [],
      ),
    'updateSocialLink' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateTestimonial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };