/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'metaTitle' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
});
export const SeoSetting = IDL.Record({
  'metaDescription' : IDL.Text,
  'page' : IDL.Text,
  'metaTitle' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Skill = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'experience' : IDL.Int,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addService' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addSkill' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBlog' : IDL.Func([IDL.Nat], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteSeoSetting' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'deleteSkill' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'leadCount' : IDL.Nat,
          'projectCount' : IDL.Nat,
          'blogCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSeoSettingByPage' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SeoSetting)],
      ['query'],
    ),
  'getSeoSettings' : IDL.Func([], [IDL.Vec(SeoSetting)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSeoSetting' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBlog' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateSkill' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [], []),
  'updateTestimonial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'metaTitle' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
  });
  const SeoSetting = IDL.Record({
    'metaDescription' : IDL.Text,
    'page' : IDL.Text,
    'metaTitle' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Skill = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'experience' : IDL.Int,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'addService' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addSkill' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBlog' : IDL.Func([IDL.Nat], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteSeoSetting' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'deleteSkill' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'leadCount' : IDL.Nat,
            'projectCount' : IDL.Nat,
            'blogCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSeoSettingByPage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SeoSetting)],
        ['query'],
      ),
    'getSeoSettings' : IDL.Func([], [IDL.Vec(SeoSetting)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSeoSetting' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateBlog' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateSkill' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [], []),
    'updateTestimonial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };