/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'slug' : string,
  'metaTitle' : string,
  'timestamp' : bigint,
}
export type ClaimAdminResult = { 'adminAlreadyExists' : Principal } |
  { 'adminClaimed' : null } |
  { 'anonymousPrincipal' : null };
export type ExternalBlob = Uint8Array;
export interface Lead {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Project {
  'id' : bigint,
  'url' : string,
  'categoryId' : [] | [bigint],
  'title' : string,
  'description' : string,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface ProjectCategory {
  'id' : bigint,
  'name' : string,
  'slug' : string,
}
export interface SeoSetting {
  'metaDescription' : string,
  'page' : string,
  'metaTitle' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export interface Skill {
  'id' : bigint,
  'name' : string,
  'experience' : bigint,
  'category' : SkillCategory,
}
export type SkillCategory = { 'security' : null } |
  { 'secondary' : null } |
  { 'primary' : null } |
  { 'additional' : null };
export interface SocialLink {
  'id' : bigint,
  'url' : string,
  'icon' : string,
  'platform' : SocialPlatform,
  'isActive' : boolean,
}
export type SocialPlatform = { 'x' : null } |
  { 'linkedin' : null } |
  { 'github' : null };
export interface Testimonial {
  'id' : bigint,
  'author' : string,
  'message' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlog' : ActorMethod<[string, string, string, string, string], undefined>,
  'addProject' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], [] | [bigint]],
    undefined
  >,
  'addService' : ActorMethod<[string, string], undefined>,
  'addSkill' : ActorMethod<[string, bigint, SkillCategory], undefined>,
  'addTestimonial' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], ClaimAdminResult>,
  'createCategory' : ActorMethod<[string, string], undefined>,
  'createSocialLink' : ActorMethod<[SocialPlatform, string, string], undefined>,
  'deleteBlog' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteSeoSetting' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteSkill' : ActorMethod<[bigint], undefined>,
  'deleteSocialLink' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getBlogBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogs' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    { 'leadCount' : bigint, 'projectCount' : bigint, 'blogCount' : bigint }
  >,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSeoSettingByPage' : ActorMethod<[string], [] | [SeoSetting]>,
  'getSeoSettings' : ActorMethod<[], Array<SeoSetting>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<ProjectCategory>>,
  'listSkills' : ActorMethod<[], Array<Skill>>,
  'listSocialLinks' : ActorMethod<[], Array<SocialLink>>,
  'processContactForm' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSeoSetting' : ActorMethod<[string, string, string], undefined>,
  'toggleSocialLink' : ActorMethod<[bigint], undefined>,
  'updateBlog' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateCategory' : ActorMethod<[bigint, string, string], undefined>,
  'updateProject' : ActorMethod<
    [bigint, string, string, string, [] | [ExternalBlob], [] | [bigint]],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, string, string], undefined>,
  'updateSkill' : ActorMethod<
    [bigint, string, bigint, SkillCategory],
    undefined
  >,
  'updateSocialLink' : ActorMethod<[bigint, string, string], undefined>,
  'updateTestimonial' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];